image:
  file: .gitpod.Dockerfile
tasks:
  - init:
      cabal repl
vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
    - dracula-theme.theme-dracula
    - GitHub.vscode-pull-request-github
    - vscode-icons-team.vscode-icons